run:
	gcc *.c
	./a.out input1.txt 20 500
	./a.out input1.txt 234
	echo "\n"	
	./a.out input1.txt 100 500
	./a.out input1.txt 234
	echo "\n"
	./a.out input1.txt 1000 50000
	./a.out input1.txt 234
	echo "\n"	
	./a.out input1.txt 10000 1000000
	./a.out input1.txt 2344
	echo "\n"	
	./a.out input1.txt 100000 5012412
	./a.out input1.txt 23124
	echo "\n"	
	./a.out input1.txt 1000000 2141500
	./a.out input1.txt 23445
	echo "\n"
